FROM php:8.0-apache

RUN apt-get update -y && apt-get install -y \
  libicu-dev \
  libpng-dev \
  libzip-dev \
  zip \
  unzip \
  vim \
  git

RUN docker-php-ext-install mysqli pdo_mysql gd opcache zip

COPY config/php/php.ini /usr/local/etc/php/

COPY config/ssl/local.app.crt /etc/ssl/certs/
COPY config/ssl/local.app.key /etc/ssl/private/

ENV APACHE_RUN_USER www-data
ENV APACHE_RUN_GROUP www-data
ENV APACHE_LOG_DIR /var/log/apache2

RUN a2enmod headers
RUN a2enmod rewrite
RUN a2enmod ssl
RUN a2enmod actions

RUN rm -rf /etc/apache2/sites-enabled/*
COPY config/apache/sites-enabled /etc/apache2/sites-enabled

RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
